# Makefile - makefile for public_html/humor
# $Id: Makefile 550 2005-08-06 17:16:08Z ranga $

TITLE = Humor
MKDIR = ../mk
POST_CLEAN = rmindex
RULE_INDEX = genindex

all: $(RULE_INDEX)

include $(MKDIR)/common.mk

